# Generated by Django 4.2.11 on 2024-06-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='name',
            new_name='Category',
        ),
    ]
