# Generated by Django 4.2.11 on 2024-06-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodels',
            name='Category',
            field=models.ManyToManyField(to='category.categorymodel'),
        ),
    ]
